name: thejackmag
recipe: symfony
services:
  node:
    type: node:16
    port: 8080
    globals:
      yarn: latest
config:
  webroot: public
tooling:
  npm:
    service: node
  npx:
    service: node
  yarn:
    service: node
