#!/bin/bash

SSH_ACCOUNT="elpadi@thejackmag.com"
SERVER_PATH="/home1/elpadi/symfony"
SSH_PORT=2222

upload_dir() {
    dirPathNoSlash=$(echo "$1" | sed 's:/*$::')
	echo "Uploading dir $1"
    rsync -avuzh --delete-after --port=$SSH_PORT "$dirPathNoSlash/" "$SSH_ACCOUNT:$SERVER_PATH/$dirPathNoSlash/"
}

upload_file() {
	echo "Uploading file $1"
	scp -P $SSH_PORT -r "$1" "$SSH_ACCOUNT:$SERVER_PATH/$1"
}

download_file() {
	echo "Downloading $1"
	scp -P $SSH_PORT -r "$SSH_ACCOUNT:$SERVER_PATH/$1" "$1"
}

if [[ $# == 0 ]]; then
	ssh -p $SSH_PORT $SSH_ACCOUNT
	exit 0
fi

while [[ $# > 0 ]]; do
	if [[ -z $ACTION ]]; then
		if [[ "$1" != "u" ]] && [[ "$1" != "d" ]]; then
			echo "First param must be 'u' or 'd'"
			exit 1
		fi
		ACTION="$1"
	else
		if [[ "$ACTION" == "u" ]]; then
            if [[ -d "$1" ]]; then
                upload_dir "$1"
            else
                upload_file "$1"
            fi
        fi
		if [[ "$ACTION" == "d" ]]; then
            download_file "$1"
        fi
	fi
	shift
done

exit 0
