#!/bin/bash

SITE_URL="elpadi@thejackmag.com"
SSH_PORT=2222

if [[ $ENV == "staging" ]]; then
    SITE_REMOTE_DIR="/home1/elpadi/staging.thejackmag.com/symfony"
elif [[ $ENV == "prod" ]]; then
    SITE_REMOTE_DIR="/home1/elpadi/symfony"
fi

. "$HOME/Work/elpadi/shell-scripts/site-ssh"
