#!/bin/bash

SITE_URL="elpadi@thejackmag.com"
SSH_PORT=2222

if [[ $ENV == "staging" ]]; then
    SITE_REMOTE_DIR="/home1/elpadi/staging.thejackmag.com/symfony/public"
elif [[ $ENV == "prod" ]]; then
    SITE_REMOTE_DIR="/home1/elpadi/public_html"
    echo -e "This uploads to /public_html. Remember you must also upload to /symfony/public.\n"
fi

. "$HOME/Work/elpadi/shell-scripts/site-ssh"
